export const MOCK_ITEMS = {
    "orderSimulate": {
        "return": {
            "type": "",
            "messageClass": "",
            "text": ""
        },  
        "header": {
            "subTotal": "252.0000",
            "totalDiscounts": "0",
            "totalFees": "35.0000",
            "totalNetPrice": "287.0000",
            "totalDeposits": "0",
            "totalTaxes": "0",
            "totalPrice": "287.0000",
            "totalQuantity": "0000000003"
        },
        "item": [
            {
                "number": "000010",
                "highLevel": "000000",
                "material": "000000000000150565",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "CS",
                "salesUnit": "CS",
                "category": "ZN41",
                "text": "18.6Z CN 12LS TS MON NRG UBMON NK.",
                "netValue": "82.0000",
                "currency": "USD",
                "subtotal1": "72.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "10.0000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "72.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "72.0000",
                "totalDiscounts": "0",
                "totalFees": "10.0000",
                "totalNetPrice": "82.0000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "82.0000"
            },
            {
                "number": "000020",
                "highLevel": "000000",
                "material": "000000000000100287",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P SPRITE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "70.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "70.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "70.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            },
            {
                "number": "000030",
                "highLevel": "000000",
                "material": "000000000000100281",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P HC DT COKE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "90.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "90.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "90.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            },
            {
                "number": "000040",
                "highLevel": "000000",
                "material": "000000000000100278",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P HC COKE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "20.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "20.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "20.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            }
        ],
        "moq": {},
        "condition": [
            {
                "itemNumber": "000010",
                "type": "ZPRE",
                "rate": "72.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "72.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000010",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "72.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000010",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            }
        ]
    }
};

export const MOCK_ITEMS_WITH_MOV = {
    "orderSimulate": {
        "return": {
            "type": "",
            "messageClass": "",
            "text": ""
        },  
        "header": {
            "subTotal": "252.0000",
            "totalDiscounts": "0",
            "totalFees": "35.0000",
            "totalNetPrice": "287.0000",
            "totalDeposits": "0",
            "totalTaxes": "0",
            "totalPrice": "287.0000",
            "totalQuantity": "0000000003"
        },
        "item": [
            {
                "number": "000010",
                "highLevel": "000000",
                "material": "000000000000150565",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "CS",
                "salesUnit": "CS",
                "category": "ZN41",
                "text": "18.6Z CN 12LS TS MON NRG UBMON NK.",
                "netValue": "82.0000",
                "currency": "USD",
                "subtotal1": "72.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "10.0000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "72.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "72.0000",
                "totalDiscounts": "0",
                "totalFees": "10.0000",
                "totalNetPrice": "82.0000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "82.0000"
            },
            {
                "number": "000020",
                "highLevel": "000000",
                "material": "000000000000100287",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P SPRITE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "70.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "70.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "70.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            },
            {
                "number": "000030",
                "highLevel": "000000",
                "material": "000000000000100281",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P HC DT COKE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "90.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "90.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "90.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            },
            {
                "number": "000040",
                "highLevel": "000000",
                "material": "000000000000100278",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P HC COKE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "20.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "20.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "20.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            }
        ],
        "moq": {},
        "condition": [
            {
                "itemNumber": "000010",
                "type": "ZPRE",
                "rate": "72.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "72.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000010",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "72.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000010",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000010",
                "type": "ZMOV",
                "rate": "50.000000000",
                "rateUnit": "CAD",
                "pricingUnit": "0",
                "unit": "",
                "value": "50.000000000",
                "currency": "CAD",
                "isInactive": ""
            }
        ]
    }
}


export const MOCK_ITEMS_WITH_MOQ = {
    "orderSimulate": {
        "return": {
            "type": "",
            "messageClass": "",
            "text": ""
        },  
        "header": {
            "subTotal": "252.0000",
            "totalDiscounts": "0",
            "totalFees": "35.0000",
            "totalNetPrice": "287.0000",
            "totalDeposits": "0",
            "totalTaxes": "0",
            "totalPrice": "287.0000",
            "totalQuantity": "0000000003"
        },
        "item": [
            {
                "number": "000010",
                "highLevel": "000000",
                "material": "000000000000150565",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "CS",
                "salesUnit": "CS",
                "category": "ZN41",
                "text": "18.6Z CN 12LS TS MON NRG UBMON NK.",
                "netValue": "82.0000",
                "currency": "USD",
                "subtotal1": "72.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "10.0000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "72.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "72.0000",
                "totalDiscounts": "0",
                "totalFees": "10.0000",
                "totalNetPrice": "82.0000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "82.0000"
            },
            {
                "number": "000020",
                "highLevel": "000000",
                "material": "000000000000100287",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P SPRITE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "70.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "70.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "70.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            },
            {
                "number": "000030",
                "highLevel": "000000",
                "material": "000000000000100281",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P HC DT COKE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "90.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "90.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "90.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            },
            {
                "number": "000040",
                "highLevel": "000000",
                "material": "000000000000100278",
                "requestedQuantity": "1.000",
                "requestedQuantityUom": "EA",
                "salesUnit": "EA",
                "category": "ZN41",
                "text": "12Z CN 6P HC COKE",
                "netValue": "102.5000",
                "currency": "USD",
                "subtotal1": "20.0000",
                "subtotal2": "0",
                "subtotal3": "0",
                "subtotal4": "0",
                "subtotal5": "0",
                "subtotal6": "0",
                "subtotal7": "0",
                "subtotal8": "0",
                "subtotal9": "0",
                "subtotal10": "12.5000",
                "subtotal11": "0",
                "subtotal12": "0",
                "subtotal13": "20.0000",
                "subtotal14": "0",
                "subtotal15": "0",
                "subtotal16": "0",
                "subtotal17": "0",
                "salesTax": "0",
                "plant": "K019",
                "subTotal": "20.0000",
                "totalDiscounts": "0",
                "totalFees": "12.5000",
                "totalNetPrice": "102.5000",
                "totalDeposits": "0",
                "totalTaxes": "0",
                "totalPrice": "102.5000"
            }
        ],
        "moq": [
            {
                "scaleQuantity": "1.000",
                "fee": "10.00"
            },
            {
                "scaleQuantity": "11.000",
                "fee": "0.00"
            }
        ],
        "condition": [
            {
                "itemNumber": "000010",
                "type": "ZPRE",
                "rate": "72.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "72.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000010",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "72.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000010",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "CS",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000020",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000030",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZPRE",
                "rate": "90.000000000",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZEAW",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "90.000000000",
                "currency": "USD",
                "isInactive": ""
            },
            {
                "itemNumber": "000040",
                "type": "ZCRO",
                "rate": "0",
                "rateUnit": "USD",
                "pricingUnit": "1",
                "unit": "EA",
                "value": "0",
                "currency": "USD",
                "isInactive": ""
            }
        ]
    }
};